from __future__ import annotations

from pydantic import BaseModel


class ToolBgConfig(BaseModel):
    pending: str
    success: str
    error: str


class BadgeColorConfig(BaseModel):
    bg: str
    label: str


class ColorsConfig(BaseModel):
    dim: str
    muted: str
    title: str
    spinner: str
    accent: str
    info: str
    markdown_heading: str
    markdown_code: str
    selected: str
    error: str
    notice: str
    diff_added: str
    diff_removed: str
    tool_bg: ToolBgConfig
    badge: BadgeColorConfig
    running: str
    success: str
    failed: str
    bg: str
    fg: str
    panel: str
    panel_alt: str
    panel_user: str
    border: str


class ThemeConfig(BaseModel):
    id: str
    label: str
    colors: ColorsConfig


_THEMES: dict[str, ThemeConfig] = {
    "gruvbox-dark": ThemeConfig(
        id="gruvbox-dark",
        label="Gruvbox Dark",
        colors=ColorsConfig(
            bg="#282828",
            fg="#ebdbb2",
            dim="#7c6f64",
            muted="#a89984",
            title="#fabd2f",
            spinner="#83a598",
            accent="#83a598",
            info="#fabd2f",
            markdown_heading="#fabd2f",
            markdown_code="#8ec07c",
            selected="#8ec07c",
            error="#fb4934",
            notice="#fe8019",
            diff_added="#b8bb26",
            diff_removed="#fb4934",
            tool_bg=ToolBgConfig(pending="#32302f", success="#3c3836", error="#3c2f2f"),
            badge=BadgeColorConfig(bg="#3c3836", label="#d3869b"),
            running="#458588",
            success="#98971a",
            failed="#cc241d",
            panel="#3c3836",
            panel_alt="#32302f",
            panel_user="#504945",
            border="#504945",
        ),
    ),
    "gruvbox-light": ThemeConfig(
        id="gruvbox-light",
        label="Gruvbox Light",
        colors=ColorsConfig(
            bg="#fbf1c7",
            fg="#3c3836",
            dim="#a89984",
            muted="#7c6f64",
            title="#b57614",
            spinner="#076678",
            accent="#076678",
            info="#b57614",
            markdown_heading="#b57614",
            markdown_code="#427b58",
            selected="#427b58",
            error="#9d0006",
            notice="#af3a03",
            diff_added="#79740e",
            diff_removed="#9d0006",
            tool_bg=ToolBgConfig(pending="#f2e5bc", success="#ebdbb2", error="#f3d9d4"),
            badge=BadgeColorConfig(bg="#ebdbb2", label="#b16286"),
            running="#458588",
            success="#79740e",
            failed="#9d0006",
            panel="#ebdbb2",
            panel_alt="#f2e5bc",
            panel_user="#d5c4a1",
            border="#d5c4a1",
        ),
    ),
    "catppuccin-mocha": ThemeConfig(
        id="catppuccin-mocha",
        label="Catppuccin Mocha",
        colors=ColorsConfig(
            bg="#1e1e2e",
            fg="#cdd6f4",
            dim="#6c7086",
            muted="#a6adc8",
            title="#f5e0dc",
            spinner="#89b4fa",
            accent="#89b4fa",
            info="#f9e2af",
            markdown_heading="#f9e2af",
            markdown_code="#94e2d5",
            selected="#a6e3a1",
            error="#f38ba8",
            notice="#fab387",
            diff_added="#a6e3a1",
            diff_removed="#f38ba8",
            tool_bg=ToolBgConfig(pending="#313244", success="#2b3a33", error="#3d2f38"),
            badge=BadgeColorConfig(bg="#313244", label="#cba6f7"),
            running="#89b4fa",
            success="#a6e3a1",
            failed="#f38ba8",
            panel="#313244",
            panel_alt="#45475a",
            panel_user="#3b3f57",
            border="#45475a",
        ),
    ),
    "catppuccin-latte": ThemeConfig(
        id="catppuccin-latte",
        label="Catppuccin Latte",
        colors=ColorsConfig(
            bg="#eff1f5",
            fg="#4c4f69",
            dim="#9ca0b0",
            muted="#7c7f93",
            title="#dc8a78",
            spinner="#1e66f5",
            accent="#1e66f5",
            info="#df8e1d",
            markdown_heading="#df8e1d",
            markdown_code="#179299",
            selected="#40a02b",
            error="#d20f39",
            notice="#fe640b",
            diff_added="#40a02b",
            diff_removed="#d20f39",
            tool_bg=ToolBgConfig(pending="#e6e9ef", success="#dfe8dc", error="#f2d8dd"),
            badge=BadgeColorConfig(bg="#e6e9ef", label="#8839ef"),
            running="#1e66f5",
            success="#40a02b",
            failed="#d20f39",
            panel="#e6e9ef",
            panel_alt="#dce0e8",
            panel_user="#ccd0da",
            border="#ccd0da",
        ),
    ),
    "catppuccin-frappe": ThemeConfig(
        id="catppuccin-frappe",
        label="Catppuccin Frappe",
        colors=ColorsConfig(
            bg="#303446",
            fg="#c6d0f5",
            dim="#737994",
            muted="#a5adce",
            title="#ca9ee6",
            spinner="#8da4e2",
            accent="#f4b8e4",
            info="#81c8be",
            markdown_heading="#ca9ee6",
            markdown_code="#a6d189",
            selected="#a6d189",
            error="#e78284",
            notice="#e5c890",
            diff_added="#a6d189",
            diff_removed="#e78284",
            tool_bg=ToolBgConfig(pending="#232634", success="#29342b", error="#3a2a31"),
            badge=BadgeColorConfig(bg="#232634", label="#ca9ee6"),
            running="#8da4e2",
            success="#a6d189",
            failed="#e78284",
            panel="#292c3c",
            panel_alt="#232634",
            panel_user="#626880",
            border="#414559",
        ),
    ),
    "catppuccin-macchiato": ThemeConfig(
        id="catppuccin-macchiato",
        label="Catppuccin Macchiato",
        colors=ColorsConfig(
            bg="#24273a",
            fg="#cad3f5",
            dim="#6e738d",
            muted="#a5adcb",
            title="#c6a0f6",
            spinner="#8aadf4",
            accent="#f5bde6",
            info="#8bd5ca",
            markdown_heading="#c6a0f6",
            markdown_code="#a6da95",
            selected="#a6da95",
            error="#ed8796",
            notice="#eed49f",
            diff_added="#a6da95",
            diff_removed="#ed8796",
            tool_bg=ToolBgConfig(pending="#181926", success="#29342b", error="#3a2a31"),
            badge=BadgeColorConfig(bg="#181926", label="#c6a0f6"),
            running="#8aadf4",
            success="#a6da95",
            failed="#ed8796",
            panel="#1e2030",
            panel_alt="#181926",
            panel_user="#5b6078",
            border="#363a4f",
        ),
    ),
    "dracula": ThemeConfig(
        id="dracula",
        label="Dracula",
        colors=ColorsConfig(
            bg="#282a36",
            fg="#f8f8f2",
            dim="#6272a4",
            muted="#bd93f9",
            title="#ff79c6",
            spinner="#8be9fd",
            accent="#8be9fd",
            info="#f1fa8c",
            markdown_heading="#ff79c6",
            markdown_code="#50fa7b",
            selected="#50fa7b",
            error="#ff5555",
            notice="#ffb86c",
            diff_added="#50fa7b",
            diff_removed="#ff5555",
            tool_bg=ToolBgConfig(pending="#343746", success="#2f3b35", error="#43303a"),
            badge=BadgeColorConfig(bg="#343746", label="#bd93f9"),
            running="#8be9fd",
            success="#50fa7b",
            failed="#ff5555",
            panel="#343746",
            panel_alt="#3a3d4d",
            panel_user="#44475a",
            border="#44475a",
        ),
    ),
    "everforest": ThemeConfig(
        id="everforest",
        label="Everforest",
        colors=ColorsConfig(
            bg="#2d353b",
            fg="#d3c6aa",
            dim="#859289",
            muted="#7a8478",
            title="#7fbbb3",
            spinner="#a7c080",
            accent="#d699b6",
            info="#83c092",
            markdown_heading="#d699b6",
            markdown_code="#a7c080",
            selected="#a7c080",
            error="#e67e80",
            notice="#e69875",
            diff_added="#4fd6be",
            diff_removed="#c53b53",
            tool_bg=ToolBgConfig(pending="#343f44", success="#20303b", error="#37222c"),
            badge=BadgeColorConfig(bg="#343f44", label="#7fbbb3"),
            running="#a7c080",
            success="#a7c080",
            failed="#e67e80",
            panel="#333c43",
            panel_alt="#343f44",
            panel_user="#7a8478",
            border="#859289",
        ),
    ),
    "flexoki": ThemeConfig(
        id="flexoki",
        label="Flexoki",
        colors=ColorsConfig(
            bg="#100F0F",
            fg="#CECDC3",
            dim="#575653",
            muted="#6F6E69",
            title="#4385BE",
            spinner="#DA702C",
            accent="#8B7EC8",
            info="#3AA99F",
            markdown_heading="#8B7EC8",
            markdown_code="#3AA99F",
            selected="#879A39",
            error="#D14D41",
            notice="#DA702C",
            diff_added="#879A39",
            diff_removed="#D14D41",
            tool_bg=ToolBgConfig(pending="#282726", success="#1A2D1A", error="#2D1A1A"),
            badge=BadgeColorConfig(bg="#282726", label="#4385BE"),
            running="#DA702C",
            success="#879A39",
            failed="#D14D41",
            panel="#1C1B1A",
            panel_alt="#282726",
            panel_user="#403E3C",
            border="#575653",
        ),
    ),
    "github-dark": ThemeConfig(
        id="github-dark",
        label="GitHub Dark",
        colors=ColorsConfig(
            bg="#0d1117",
            fg="#c9d1d9",
            dim="#6e7681",
            muted="#8b949e",
            title="#58a6ff",
            spinner="#58a6ff",
            accent="#58a6ff",
            info="#d29922",
            markdown_heading="#79c0ff",
            markdown_code="#a5d6ff",
            selected="#3fb950",
            error="#f85149",
            notice="#db6d28",
            diff_added="#3fb950",
            diff_removed="#f85149",
            tool_bg=ToolBgConfig(pending="#161b22", success="#132a1b", error="#2d1f24"),
            badge=BadgeColorConfig(bg="#161b22", label="#bc8cff"),
            running="#58a6ff",
            success="#3fb950",
            failed="#f85149",
            panel="#161b22",
            panel_alt="#1f2630",
            panel_user="#21262d",
            border="#30363d",
        ),
    ),
    "github-light": ThemeConfig(
        id="github-light",
        label="GitHub Light",
        colors=ColorsConfig(
            bg="#ffffff",
            fg="#1f2328",
            dim="#8c959f",
            muted="#656d76",
            title="#0969da",
            spinner="#0969da",
            accent="#0969da",
            info="#9a6700",
            markdown_heading="#0969da",
            markdown_code="#1a7f37",
            selected="#1a7f37",
            error="#cf222e",
            notice="#bc4c00",
            diff_added="#1a7f37",
            diff_removed="#cf222e",
            tool_bg=ToolBgConfig(pending="#f6f8fa", success="#eaf5ec", error="#f8e6e8"),
            badge=BadgeColorConfig(bg="#f6f8fa", label="#8250df"),
            running="#0969da",
            success="#1a7f37",
            failed="#cf222e",
            panel="#f6f8fa",
            panel_alt="#eaeef2",
            panel_user="#eef2f6",
            border="#d0d7de",
        ),
    ),
    "tokyo-night": ThemeConfig(
        id="tokyo-night",
        label="Tokyo Night",
        colors=ColorsConfig(
            bg="#1a1b26",
            fg="#c0caf5",
            dim="#565f89",
            muted="#a9b1d6",
            title="#bb9af7",
            spinner="#7aa2f7",
            accent="#7aa2f7",
            info="#e0af68",
            markdown_heading="#e0af68",
            markdown_code="#73daca",
            selected="#9ece6a",
            error="#f7768e",
            notice="#ff9e64",
            diff_added="#9ece6a",
            diff_removed="#f7768e",
            tool_bg=ToolBgConfig(pending="#24283b", success="#243638", error="#3a2734"),
            badge=BadgeColorConfig(bg="#24283b", label="#bb9af7"),
            running="#7aa2f7",
            success="#9ece6a",
            failed="#f7768e",
            panel="#24283b",
            panel_alt="#2f354d",
            panel_user="#313a5f",
            border="#3b4261",
        ),
    ),
    "tokyo-day": ThemeConfig(
        id="tokyo-day",
        label="Tokyo Day",
        colors=ColorsConfig(
            bg="#d5d6db",
            fg="#3760bf",
            dim="#848cb5",
            muted="#6172b0",
            title="#7847bd",
            spinner="#2e7de9",
            accent="#2e7de9",
            info="#8c6c3e",
            markdown_heading="#8c6c3e",
            markdown_code="#007197",
            selected="#587539",
            error="#f52a65",
            notice="#b15c00",
            diff_added="#587539",
            diff_removed="#f52a65",
            tool_bg=ToolBgConfig(pending="#cbccd1", success="#c7d8cb", error="#dec7cf"),
            badge=BadgeColorConfig(bg="#cbccd1", label="#9854f1"),
            running="#2e7de9",
            success="#587539",
            failed="#f52a65",
            panel="#cbccd1",
            panel_alt="#c4c8da",
            panel_user="#b7c5e3",
            border="#b4b5b9",
        ),
    ),
    "kanagawa": ThemeConfig(
        id="kanagawa",
        label="Kanagawa",
        colors=ColorsConfig(
            bg="#1F1F28",
            fg="#DCD7BA",
            dim="#54546D",
            muted="#727169",
            title="#957FB8",
            spinner="#7E9CD8",
            accent="#D27E99",
            info="#76946A",
            markdown_heading="#957FB8",
            markdown_code="#98BB6C",
            selected="#98BB6C",
            error="#E82424",
            notice="#D7A657",
            diff_added="#98BB6C",
            diff_removed="#E82424",
            tool_bg=ToolBgConfig(pending="#363646", success="#252E25", error="#362020"),
            badge=BadgeColorConfig(bg="#363646", label="#957FB8"),
            running="#7E9CD8",
            success="#98BB6C",
            failed="#E82424",
            panel="#2A2A37",
            panel_alt="#363646",
            panel_user="#363646",
            border="#54546D",
        ),
    ),
    "one-dark": ThemeConfig(
        id="one-dark",
        label="One Dark",
        colors=ColorsConfig(
            bg="#282c34",
            fg="#abb2bf",
            dim="#5c6370",
            muted="#7f848e",
            title="#c678dd",
            spinner="#61afef",
            accent="#61afef",
            info="#e5c07b",
            markdown_heading="#e5c07b",
            markdown_code="#56b6c2",
            selected="#98c379",
            error="#e06c75",
            notice="#d19a66",
            diff_added="#98c379",
            diff_removed="#e06c75",
            tool_bg=ToolBgConfig(pending="#353b45", success="#33403b", error="#442f36"),
            badge=BadgeColorConfig(bg="#353b45", label="#c678dd"),
            running="#61afef",
            success="#98c379",
            failed="#e06c75",
            panel="#353b45",
            panel_alt="#3e4451",
            panel_user="#404754",
            border="#4b5263",
        ),
    ),
    "one-light": ThemeConfig(
        id="one-light",
        label="One Light",
        colors=ColorsConfig(
            bg="#fafafa",
            fg="#383a42",
            dim="#9ca0a4",
            muted="#696c77",
            title="#a626a4",
            spinner="#4078f2",
            accent="#4078f2",
            info="#c18401",
            markdown_heading="#c18401",
            markdown_code="#0184bc",
            selected="#50a14f",
            error="#e45649",
            notice="#986801",
            diff_added="#50a14f",
            diff_removed="#e45649",
            tool_bg=ToolBgConfig(pending="#f0f0f1", success="#e6f1e6", error="#f5e3e1"),
            badge=BadgeColorConfig(bg="#f0f0f1", label="#a626a4"),
            running="#4078f2",
            success="#50a14f",
            failed="#e45649",
            panel="#f0f0f1",
            panel_alt="#e5e5e6",
            panel_user="#dfe1e6",
            border="#d0d0d2",
        ),
    ),
    "nord": ThemeConfig(
        id="nord",
        label="Nord",
        colors=ColorsConfig(
            bg="#2e3440",
            fg="#d8dee9",
            dim="#616e88",
            muted="#81a1c1",
            title="#88c0d0",
            spinner="#5e81ac",
            accent="#5e81ac",
            info="#ebcb8b",
            markdown_heading="#88c0d0",
            markdown_code="#a3be8c",
            selected="#a3be8c",
            error="#bf616a",
            notice="#d08770",
            diff_added="#a3be8c",
            diff_removed="#bf616a",
            tool_bg=ToolBgConfig(pending="#3b4252", success="#364238", error="#46343b"),
            badge=BadgeColorConfig(bg="#3b4252", label="#b48ead"),
            running="#5e81ac",
            success="#a3be8c",
            failed="#bf616a",
            panel="#3b4252",
            panel_alt="#434c5e",
            panel_user="#4c566a",
            border="#4c566a",
        ),
    ),
    "nightowl": ThemeConfig(
        id="nightowl",
        label="Night Owl",
        colors=ColorsConfig(
            bg="#011627",
            fg="#d6deeb",
            dim="#5f7e97",
            muted="#5f7e97",
            title="#7fdbca",
            spinner="#82AAFF",
            accent="#c792ea",
            info="#82AAFF",
            markdown_heading="#82AAFF",
            markdown_code="#c5e478",
            selected="#c5e478",
            error="#EF5350",
            notice="#ecc48d",
            diff_added="#c5e478",
            diff_removed="#EF5350",
            tool_bg=ToolBgConfig(pending="#0b253a", success="#0a2e1a", error="#2d1b1b"),
            badge=BadgeColorConfig(bg="#0b253a", label="#7fdbca"),
            running="#82AAFF",
            success="#c5e478",
            failed="#EF5350",
            panel="#0b253a",
            panel_alt="#0b253a",
            panel_user="#5f7e97",
            border="#5f7e97",
        ),
    ),
    "monokai": ThemeConfig(
        id="monokai",
        label="Monokai",
        colors=ColorsConfig(
            bg="#272822",
            fg="#f8f8f2",
            dim="#3e3d32",
            muted="#75715e",
            title="#ae81ff",
            spinner="#66d9ef",
            accent="#a6e22e",
            info="#fd971f",
            markdown_heading="#f92672",
            markdown_code="#a6e22e",
            selected="#a6e22e",
            error="#f92672",
            notice="#e6db74",
            diff_added="#a6e22e",
            diff_removed="#f92672",
            tool_bg=ToolBgConfig(pending="#3e3d32", success="#1a3a1a", error="#3a1a1a"),
            badge=BadgeColorConfig(bg="#3e3d32", label="#ae81ff"),
            running="#66d9ef",
            success="#a6e22e",
            failed="#f92672",
            panel="#1e1f1c",
            panel_alt="#3e3d32",
            panel_user="#1e1f1c",
            border="#3e3d32",
        ),
    ),
    "solarized-dark": ThemeConfig(
        id="solarized-dark",
        label="Solarized Dark",
        colors=ColorsConfig(
            bg="#002b36",
            fg="#93a1a1",
            dim="#586e75",
            muted="#657b83",
            title="#b58900",
            spinner="#268bd2",
            accent="#268bd2",
            info="#cb4b16",
            markdown_heading="#b58900",
            markdown_code="#2aa198",
            selected="#859900",
            error="#dc322f",
            notice="#cb4b16",
            diff_added="#859900",
            diff_removed="#dc322f",
            tool_bg=ToolBgConfig(pending="#073642", success="#183c37", error="#402c32"),
            badge=BadgeColorConfig(bg="#073642", label="#6c71c4"),
            running="#268bd2",
            success="#859900",
            failed="#dc322f",
            panel="#073642",
            panel_alt="#0b3a45",
            panel_user="#12404b",
            border="#194955",
        ),
    ),
    "solarized-light": ThemeConfig(
        id="solarized-light",
        label="Solarized Light",
        colors=ColorsConfig(
            bg="#fdf6e3",
            fg="#657b83",
            dim="#93a1a1",
            muted="#586e75",
            title="#b58900",
            spinner="#268bd2",
            accent="#268bd2",
            info="#cb4b16",
            markdown_heading="#b58900",
            markdown_code="#2aa198",
            selected="#859900",
            error="#dc322f",
            notice="#cb4b16",
            diff_added="#859900",
            diff_removed="#dc322f",
            tool_bg=ToolBgConfig(pending="#eee8d5", success="#e5eed4", error="#f2ddda"),
            badge=BadgeColorConfig(bg="#eee8d5", label="#6c71c4"),
            running="#268bd2",
            success="#859900",
            failed="#dc322f",
            panel="#eee8d5",
            panel_alt="#e7e1cf",
            panel_user="#e2dccb",
            border="#d8d1bf",
        ),
    ),
    "ayu": ThemeConfig(
        id="ayu",
        label="Ayu",
        colors=ColorsConfig(
            bg="#0B0E14",
            fg="#BFBDB6",
            dim="#6C7380",
            muted="#565B66",
            title="#D2A6FF",
            spinner="#59C2FF",
            accent="#E6B450",
            info="#39BAE6",
            markdown_heading="#D2A6FF",
            markdown_code="#AAD94C",
            selected="#7FD962",
            error="#D95757",
            notice="#E6B673",
            diff_added="#7FD962",
            diff_removed="#F26D78",
            tool_bg=ToolBgConfig(pending="#0D1017", success="#20303b", error="#37222c"),
            badge=BadgeColorConfig(bg="#0D1017", label="#D2A6FF"),
            running="#59C2FF",
            success="#7FD962",
            failed="#D95757",
            panel="#0F131A",
            panel_alt="#0D1017",
            panel_user="#11151C",
            border="#6C7380",
        ),
    ),
    "palenight": ThemeConfig(
        id="palenight",
        label="Palenight",
        colors=ColorsConfig(
            bg="#292d3e",
            fg="#a6accd",
            dim="#32364a",
            muted="#676e95",
            title="#c792ea",
            spinner="#82aaff",
            accent="#89ddff",
            info="#f78c6c",
            markdown_heading="#c792ea",
            markdown_code="#c3e88d",
            selected="#c3e88d",
            error="#f07178",
            notice="#ffcb6b",
            diff_added="#c3e88d",
            diff_removed="#f07178",
            tool_bg=ToolBgConfig(pending="#32364a", success="#2e3c2b", error="#3c2b2b"),
            badge=BadgeColorConfig(bg="#32364a", label="#c792ea"),
            running="#82aaff",
            success="#c3e88d",
            failed="#f07178",
            panel="#1e2132",
            panel_alt="#32364a",
            panel_user="#1e2132",
            border="#32364a",
        ),
    ),
    "rosepine": ThemeConfig(
        id="rosepine",
        label="Rosé Pine",
        colors=ColorsConfig(
            bg="#191724",
            fg="#e0def4",
            dim="#403d52",
            muted="#6e6a86",
            title="#c4a7e7",
            spinner="#9ccfd8",
            accent="#ebbcba",
            info="#9ccfd8",
            markdown_heading="#c4a7e7",
            markdown_code="#31748f",
            selected="#31748f",
            error="#eb6f92",
            notice="#f6c177",
            diff_added="#31748f",
            diff_removed="#eb6f92",
            tool_bg=ToolBgConfig(pending="#26233a", success="#1f2d3a", error="#3a1f2d"),
            badge=BadgeColorConfig(bg="#26233a", label="#c4a7e7"),
            running="#9ccfd8",
            success="#31748f",
            failed="#eb6f92",
            panel="#1f1d2e",
            panel_alt="#26233a",
            panel_user="#21202e",
            border="#403d52",
        ),
    ),
}

THEME_ORDER = [
    "ayu",
    "catppuccin-frappe",
    "catppuccin-latte",
    "catppuccin-macchiato",
    "catppuccin-mocha",
    "dracula",
    "everforest",
    "flexoki",
    "github-dark",
    "github-light",
    "gruvbox-dark",
    "gruvbox-light",
    "kanagawa",
    "monokai",
    "nightowl",
    "nord",
    "one-dark",
    "one-light",
    "palenight",
    "rosepine",
    "solarized-dark",
    "solarized-light",
    "tokyo-day",
    "tokyo-night",
]


def get_theme_ids() -> list[str]:
    return list(THEME_ORDER)


def get_theme_options() -> list[tuple[str, str]]:
    return [(theme_id, _THEMES[theme_id].label) for theme_id in THEME_ORDER]


def get_theme(theme_id: str) -> ThemeConfig:
    theme = _THEMES.get(theme_id)
    if theme is None:
        raise ValueError(f"Unknown theme: {theme_id}")
    return theme.model_copy(deep=True)
